# Generated by Django 4.2.4 on 2023-08-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stocks',
            new_name='stock',
        ),
    ]
